### ISSUE TITLE
Add CONTRIBUTION.md file

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Profile-Changer#4]

**Comment by benjamingarcia** [comment]
Hye! what did you want in your contribution rules?

**Comment by Pritom14** [comment]
Just as every simple contribution rules; first fork the project then clone
it and then commit the changes and at last send a pull request.

On 09-Oct-2017 12:43 AM, "benjamin" <notifications@github.com> wrote:

Hye! what did you want in your contribution rules?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pritom14/Profile-Changer/issues/4#issuecomment-335030749>,
or mute the thread
